
# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# See http://travis-ci.org/ for details
language: python

before_install:
 - sudo apt-get install -y python-virtualenv
 - virtualenv planemo-venv
 - . planemo-venv/bin/activate
 - pip install --upgrade pip setuptools
 - pip install planemo
# - planemo conda_init
 - wget -q --recursive -O 'Miniconda3-4.2.12-Linux-x86_64.sh' 'https://repo.continuum.io/miniconda/Miniconda3-4.2.12-Linux-x86_64.sh'
 - bash 'Miniconda3-4.2.12-Linux-x86_64.sh' -b -p /tmp/mc
 - /tmp/mc/bin/conda --version

install:
# - planemo conda_install ${TRAVIS_BUILD_DIR}/galaxy/xcms_suite --conda_ensure_channels conda-forge,r,bioconda,iuc
 - planemo conda_install --conda_prefix /tmp/mc ${TRAVIS_BUILD_DIR}/galaxy/xcms_suite

script:
# - planemo test --install_galaxy --no_cache_galaxy --conda_dependency_resolution ${TRAVIS_BUILD_DIR}/galaxy/xcms_suite
 - planemo test --install_galaxy --no_cache_galaxy --conda_dependency_resolution --conda_prefix /tmp/mc ${TRAVIS_BUILD_DIR}/galaxy/xcms_suite
