categories: [Metabolomics]
description: '[Metabolomics][W4M][ALL] Normalization (operation applied on each individual spectrum) of preprocessed data'
homepage_url: http://workflow4metabolomics.org
long_description: 'Part of the W4M project: http://workflow4metabolomics.org'
name: normalization
owner: marie-tremblay-metatoul
remote_repository_url: https://github.com/workflow4metabolomics/normalization
