definitions:
  include: &default-includes
    - test-data
    - static
    - lib.r
    - macros.xml

name: camera
owner: workflow4metabolomics
remote_repository_url: 
homepage_url: 
categories:
- Metabolomics

repositories:
  camera_annotate:
    description: '[Metabolomics][W4M][LC-MS] CAMERA R Package - Annotation - Returns annotation results (isotope peaks, adducts and fragments)'
    long_description: |
      Wrapper skript for automatic annotation of isotope peaks, adducts and
      fragments for a (grouped) xcmsSet xs. The function returns an xsAnnotate
      object.
      Part of the W4M project: http://workflow4metabolomics.org
      CAMERA: http://bioconductor.org/packages/release/bioc/html/CAMERA.html
    owner: lecorguille
    include:
      [*default-includes, abims_CAMERA_annotateDiffreport.xml, CAMERA_annotateDiffreport.r]
  # :
  #   description: ''
  #   long_description: |
  #   owner: 
  #   include:
  #     [*default-includes, , ]
  # :
  #   description: ''
  #   long_description: |
  #   owner: 
  #   include:
  #     [*default-includes, , ]

suite:
  name: suite_camera
  owner: lecorguille
  homepage_url: http://workflow4metabolomics.org
  description: '[Metabolomics][W4M][LC-MS] CAMERA R Package - Annotation - Collection of annotation related methods for mass spectrometry data'
  long_description: |
    CAMERA: Annotation of peaklists generated by xcms, rule based annotation of
    isotopes and adducts, EIC correlation based tagging of unknown adducts and
    fragments
    Part of the W4M project: http://workflow4metabolomics.org
    CAMERA: http://bioconductor.org/packages/release/bioc/html/CAMERA.html