name: massPix
categories: 
 - Metabolomics
 - Lipidomics
 - Mass Spectrometry Image Processing
description: 'Processes high resolution mass spectrometry imaging data'
homepage_url: https://github.com/hallz/massPix
long_description: 'Processes high resolution mass spectrometry imaging data,  
  performs multivariate statistics (PCA, clustering) and lipid identification.'
owner: Wanchang Lin, Zoe Hall, Julian Griffin
remote_repository_url: https://github.com/wanchanglin/massPix
