name: isolab
categories: 
 - Metabolomics
 - Lipidomics
description: 'Isotopic labelling'
homepage_url: https://github.com/RuggeroFerrazza/IsotopicLabelling
long_description: 'Analyses mass spectrometric isotopic patterns obtained
  following isotopic labelling experiments.'
owner: Wanchang Lin, Julian Griffin
remote_repository_url: https://github.com/wanchanglin/isolab
