name: physiofit_manager
owner: workflow4metabolomics
description: Handling of physiofit input files
long_description: The PhysioFit data connector merges biomass data with extracellular metabolite dynamics into PhysioFit formated input data
categories: [Metabolomics]
homepage_url: physiofit.readthedocs.io
remote_repository_url: https://github.com/MetaboHUB-MetaToul-FluxoMet/PhysioFit_Data_Manager