categories: [Metabolomics]
description: '[Metabolomics][W4M][GC-MS] metaMS R package - GC-MS data preprocessing
  using metaMS package and plotting on these datas'
homepage_url: http://workflow4metabolomics.org
long_description: 'Part of the W4M project : http://workflow4metabolomics.org metaMS
  : https://www.bioconductor.org/packages/release/bioc/html/metaMS.html MS-based metabolomics
  data processing, compound annotation pipeline and plotting.'
name: suite_metams
owner: workflow4metabolomics
remote_repository_url: https://github.com/workflow4metabolomics/metaMS