name: kmd_hmdb_data_plot
categories:
- Metabolomics
description: 'retrieves data from KMD HMDB API and produce plot and csv file'
homepage_url: https://github.com/workflow4metabolomics/tools-metabolomics
long_description: 'KMD HMDB Data Plot retrieves data from the KMD HMDB
query API, using users configurations, and plots those data with plotly'
owner: workflow4metabolomics
remote_repository_url: https://github.com/workflow4metabolomics/tools-metabolomics/blob/master/tools/kmd_hmdb_data_plot/